version: '3.5'
services:
  database:
    image: postgres:11.2-alpine
    container_name: chat.postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=chat_db
    volumes:
      - database:/var/lib/postgresql/data:delegated
    ports:
      - "54321:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d rails_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  database:
    driver: local
    name: chat_database